# THIS FILE WAS AUTOMATICALLY GENERATED BY "generate_dicts_from_data_json.py" DO NOT CHANGE MANUALLY!
# ANY CHANGE WILL BE OVERWRITTEN

from ..ids.unit_typeid import UnitTypeId
from ..ids.ability_id import AbilityId
from ..ids.upgrade_id import UpgradeId

# from ..ids.buff_id import BuffId
# from ..ids.effect_id import EffectId

from typing import Dict, Set, Union

RESEARCH_INFO: Dict[UnitTypeId, Dict[UpgradeId, Dict[str, Union[AbilityId, bool, UnitTypeId]]]] = {
    UnitTypeId.ARMORY: {
        UpgradeId.TERRANSHIPWEAPONSLEVEL1: {"ability": AbilityId.ARMORYRESEARCH_TERRANSHIPWEAPONSLEVEL1},
        UpgradeId.TERRANSHIPWEAPONSLEVEL2: {
            "ability": AbilityId.ARMORYRESEARCH_TERRANSHIPWEAPONSLEVEL2,
            "required_upgrade": UpgradeId.TERRANSHIPWEAPONSLEVEL1,
        },
        UpgradeId.TERRANSHIPWEAPONSLEVEL3: {
            "ability": AbilityId.ARMORYRESEARCH_TERRANSHIPWEAPONSLEVEL3,
            "required_upgrade": UpgradeId.TERRANSHIPWEAPONSLEVEL2,
        },
        UpgradeId.TERRANVEHICLEANDSHIPARMORSLEVEL1: {
            "ability": AbilityId.ARMORYRESEARCH_TERRANVEHICLEANDSHIPPLATINGLEVEL1
        },
        UpgradeId.TERRANVEHICLEANDSHIPARMORSLEVEL2: {
            "ability": AbilityId.ARMORYRESEARCH_TERRANVEHICLEANDSHIPPLATINGLEVEL2,
            "required_upgrade": UpgradeId.TERRANVEHICLEANDSHIPARMORSLEVEL1,
        },
        UpgradeId.TERRANVEHICLEANDSHIPARMORSLEVEL3: {
            "ability": AbilityId.ARMORYRESEARCH_TERRANVEHICLEANDSHIPPLATINGLEVEL3,
            "required_upgrade": UpgradeId.TERRANVEHICLEANDSHIPARMORSLEVEL2,
        },
        UpgradeId.TERRANVEHICLEWEAPONSLEVEL1: {"ability": AbilityId.ARMORYRESEARCH_TERRANVEHICLEWEAPONSLEVEL1},
        UpgradeId.TERRANVEHICLEWEAPONSLEVEL2: {
            "ability": AbilityId.ARMORYRESEARCH_TERRANVEHICLEWEAPONSLEVEL2,
            "required_upgrade": UpgradeId.TERRANVEHICLEWEAPONSLEVEL1,
        },
        UpgradeId.TERRANVEHICLEWEAPONSLEVEL3: {
            "ability": AbilityId.ARMORYRESEARCH_TERRANVEHICLEWEAPONSLEVEL3,
            "required_upgrade": UpgradeId.TERRANVEHICLEWEAPONSLEVEL2,
        },
    },
    UnitTypeId.BANELINGNEST: {
        UpgradeId.CENTRIFICALHOOKS: {
            "ability": AbilityId.BANELINGNESTRESEARCH_EVOLVECENTRIFICALHOOKS,
            "required_building": UnitTypeId.LAIR,
        }
    },
    UnitTypeId.BARRACKSTECHLAB: {
        UpgradeId.PUNISHERGRENADES: {"ability": AbilityId.BARRACKSTECHLABRESEARCH_RESEARCHPUNISHERGRENADES},
        UpgradeId.SHIELDWALL: {"ability": AbilityId.BARRACKSTECHLABRESEARCH_RESEARCHSHIELDWALL},
        UpgradeId.STIMPACK: {"ability": AbilityId.BARRACKSTECHLABRESEARCH_STIMPACK},
    },
    UnitTypeId.CYBERNETICSCORE: {
        UpgradeId.PROTOSSAIRARMORSLEVEL1: {
            "ability": AbilityId.CYBERNETICSCORERESEARCH_PROTOSSAIRARMORLEVEL1,
            "requires_power": True,
        },
        UpgradeId.PROTOSSAIRARMORSLEVEL2: {
            "ability": AbilityId.CYBERNETICSCORERESEARCH_PROTOSSAIRARMORLEVEL2,
            "required_building": UnitTypeId.FLEETBEACON,
            "required_upgrade": UpgradeId.PROTOSSAIRARMORSLEVEL1,
            "requires_power": True,
        },
        UpgradeId.PROTOSSAIRARMORSLEVEL3: {
            "ability": AbilityId.CYBERNETICSCORERESEARCH_PROTOSSAIRARMORLEVEL3,
            "required_building": UnitTypeId.FLEETBEACON,
            "required_upgrade": UpgradeId.PROTOSSAIRARMORSLEVEL2,
            "requires_power": True,
        },
        UpgradeId.PROTOSSAIRWEAPONSLEVEL1: {
            "ability": AbilityId.CYBERNETICSCORERESEARCH_PROTOSSAIRWEAPONSLEVEL1,
            "requires_power": True,
        },
        UpgradeId.PROTOSSAIRWEAPONSLEVEL2: {
            "ability": AbilityId.CYBERNETICSCORERESEARCH_PROTOSSAIRWEAPONSLEVEL2,
            "required_building": UnitTypeId.FLEETBEACON,
            "required_upgrade": UpgradeId.PROTOSSAIRWEAPONSLEVEL1,
            "requires_power": True,
        },
        UpgradeId.PROTOSSAIRWEAPONSLEVEL3: {
            "ability": AbilityId.CYBERNETICSCORERESEARCH_PROTOSSAIRWEAPONSLEVEL3,
            "required_building": UnitTypeId.FLEETBEACON,
            "required_upgrade": UpgradeId.PROTOSSAIRWEAPONSLEVEL2,
            "requires_power": True,
        },
        UpgradeId.WARPGATERESEARCH: {
            "ability": AbilityId.CYBERNETICSCORERESEARCH_RESEARCHWARPGATE,
            "requires_power": True,
        },
    },
    UnitTypeId.DARKSHRINE: {
        UpgradeId.DARKTEMPLARBLINKUPGRADE: {
            "ability": AbilityId.DARKSHRINERESEARCH_RESEARCHDARKTEMPLARBLINK,
            "requires_power": True,
        }
    },
    UnitTypeId.ENGINEERINGBAY: {
        UpgradeId.HISECAUTOTRACKING: {"ability": AbilityId.ENGINEERINGBAYRESEARCH_RESEARCHHISECAUTOTRACKING},
        UpgradeId.TERRANBUILDINGARMOR: {"ability": AbilityId.ENGINEERINGBAYRESEARCH_UPGRADEBUILDINGARMORLEVEL1},
        UpgradeId.TERRANINFANTRYARMORSLEVEL1: {"ability": AbilityId.ENGINEERINGBAYRESEARCH_TERRANINFANTRYARMORLEVEL1},
        UpgradeId.TERRANINFANTRYARMORSLEVEL2: {
            "ability": AbilityId.ENGINEERINGBAYRESEARCH_TERRANINFANTRYARMORLEVEL2,
            "required_building": UnitTypeId.ARMORY,
            "required_upgrade": UpgradeId.TERRANINFANTRYARMORSLEVEL1,
        },
        UpgradeId.TERRANINFANTRYARMORSLEVEL3: {
            "ability": AbilityId.ENGINEERINGBAYRESEARCH_TERRANINFANTRYARMORLEVEL3,
            "required_building": UnitTypeId.ARMORY,
            "required_upgrade": UpgradeId.TERRANINFANTRYARMORSLEVEL2,
        },
        UpgradeId.TERRANINFANTRYWEAPONSLEVEL1: {
            "ability": AbilityId.ENGINEERINGBAYRESEARCH_TERRANINFANTRYWEAPONSLEVEL1
        },
        UpgradeId.TERRANINFANTRYWEAPONSLEVEL2: {
            "ability": AbilityId.ENGINEERINGBAYRESEARCH_TERRANINFANTRYWEAPONSLEVEL2,
            "required_building": UnitTypeId.ARMORY,
            "required_upgrade": UpgradeId.TERRANINFANTRYWEAPONSLEVEL1,
        },
        UpgradeId.TERRANINFANTRYWEAPONSLEVEL3: {
            "ability": AbilityId.ENGINEERINGBAYRESEARCH_TERRANINFANTRYWEAPONSLEVEL3,
            "required_building": UnitTypeId.ARMORY,
            "required_upgrade": UpgradeId.TERRANINFANTRYWEAPONSLEVEL2,
        },
    },
    UnitTypeId.EVOLUTIONCHAMBER: {
        UpgradeId.ZERGGROUNDARMORSLEVEL1: {"ability": AbilityId.EVOLUTIONCHAMBERRESEARCH_ZERGGROUNDARMOR1},
        UpgradeId.ZERGGROUNDARMORSLEVEL2: {
            "ability": AbilityId.EVOLUTIONCHAMBERRESEARCH_ZERGGROUNDARMOR2,
            "required_building": UnitTypeId.LAIR,
            "required_upgrade": UpgradeId.ZERGGROUNDARMORSLEVEL1,
        },
        UpgradeId.ZERGGROUNDARMORSLEVEL3: {
            "ability": AbilityId.EVOLUTIONCHAMBERRESEARCH_ZERGGROUNDARMOR3,
            "required_building": UnitTypeId.HIVE,
            "required_upgrade": UpgradeId.ZERGGROUNDARMORSLEVEL2,
        },
        UpgradeId.ZERGMELEEWEAPONSLEVEL1: {"ability": AbilityId.EVOLUTIONCHAMBERRESEARCH_ZERGMELEEWEAPONS1},
        UpgradeId.ZERGMELEEWEAPONSLEVEL2: {
            "ability": AbilityId.EVOLUTIONCHAMBERRESEARCH_ZERGMELEEWEAPONS2,
            "required_building": UnitTypeId.LAIR,
            "required_upgrade": UpgradeId.ZERGMELEEWEAPONSLEVEL1,
        },
        UpgradeId.ZERGMELEEWEAPONSLEVEL3: {
            "ability": AbilityId.EVOLUTIONCHAMBERRESEARCH_ZERGMELEEWEAPONS3,
            "required_building": UnitTypeId.HIVE,
            "required_upgrade": UpgradeId.ZERGMELEEWEAPONSLEVEL2,
        },
        UpgradeId.ZERGMISSILEWEAPONSLEVEL1: {"ability": AbilityId.EVOLUTIONCHAMBERRESEARCH_ZERGMISSILEWEAPONS1},
        UpgradeId.ZERGMISSILEWEAPONSLEVEL2: {
            "ability": AbilityId.EVOLUTIONCHAMBERRESEARCH_ZERGMISSILEWEAPONS2,
            "required_building": UnitTypeId.LAIR,
            "required_upgrade": UpgradeId.ZERGMISSILEWEAPONSLEVEL1,
        },
        UpgradeId.ZERGMISSILEWEAPONSLEVEL3: {
            "ability": AbilityId.EVOLUTIONCHAMBERRESEARCH_ZERGMISSILEWEAPONS3,
            "required_building": UnitTypeId.HIVE,
            "required_upgrade": UpgradeId.ZERGMISSILEWEAPONSLEVEL2,
        },
    },
    UnitTypeId.FACTORYTECHLAB: {
        UpgradeId.CYCLONELOCKONDAMAGEUPGRADE: {
            "ability": AbilityId.FACTORYTECHLABRESEARCH_CYCLONERESEARCHLOCKONDAMAGEUPGRADE
        },
        UpgradeId.DRILLCLAWS: {
            "ability": AbilityId.FACTORYTECHLABRESEARCH_RESEARCHDRILLCLAWS,
            "required_building": UnitTypeId.ARMORY,
        },
        UpgradeId.HIGHCAPACITYBARRELS: {"ability": AbilityId.FACTORYTECHLABRESEARCH_RESEARCHHIGHCAPACITYBARRELS},
        UpgradeId.SMARTSERVOS: {
            "ability": AbilityId.FACTORYTECHLABRESEARCH_RESEARCHSMARTSERVOS,
            "required_building": UnitTypeId.ARMORY,
        },
    },
    UnitTypeId.FLEETBEACON: {
        UpgradeId.PHOENIXRANGEUPGRADE: {
            "ability": AbilityId.FLEETBEACONRESEARCH_PHOENIXRANGEUPGRADE,
            "requires_power": True,
        },
        UpgradeId.VOIDRAYSPEEDUPGRADE: {
            "ability": AbilityId.FLEETBEACONRESEARCH_RESEARCHVOIDRAYSPEEDUPGRADE,
            "requires_power": True,
        },
    },
    UnitTypeId.FORGE: {
        UpgradeId.PROTOSSGROUNDARMORSLEVEL1: {
            "ability": AbilityId.FORGERESEARCH_PROTOSSGROUNDARMORLEVEL1,
            "requires_power": True,
        },
        UpgradeId.PROTOSSGROUNDARMORSLEVEL2: {
            "ability": AbilityId.FORGERESEARCH_PROTOSSGROUNDARMORLEVEL2,
            "required_building": UnitTypeId.TWILIGHTCOUNCIL,
            "required_upgrade": UpgradeId.PROTOSSGROUNDARMORSLEVEL1,
            "requires_power": True,
        },
        UpgradeId.PROTOSSGROUNDARMORSLEVEL3: {
            "ability": AbilityId.FORGERESEARCH_PROTOSSGROUNDARMORLEVEL3,
            "required_building": UnitTypeId.TWILIGHTCOUNCIL,
            "required_upgrade": UpgradeId.PROTOSSGROUNDARMORSLEVEL2,
            "requires_power": True,
        },
        UpgradeId.PROTOSSGROUNDWEAPONSLEVEL1: {
            "ability": AbilityId.FORGERESEARCH_PROTOSSGROUNDWEAPONSLEVEL1,
            "requires_power": True,
        },
        UpgradeId.PROTOSSGROUNDWEAPONSLEVEL2: {
            "ability": AbilityId.FORGERESEARCH_PROTOSSGROUNDWEAPONSLEVEL2,
            "required_building": UnitTypeId.TWILIGHTCOUNCIL,
            "required_upgrade": UpgradeId.PROTOSSGROUNDWEAPONSLEVEL1,
            "requires_power": True,
        },
        UpgradeId.PROTOSSGROUNDWEAPONSLEVEL3: {
            "ability": AbilityId.FORGERESEARCH_PROTOSSGROUNDWEAPONSLEVEL3,
            "required_building": UnitTypeId.TWILIGHTCOUNCIL,
            "required_upgrade": UpgradeId.PROTOSSGROUNDWEAPONSLEVEL2,
            "requires_power": True,
        },
        UpgradeId.PROTOSSSHIELDSLEVEL1: {
            "ability": AbilityId.FORGERESEARCH_PROTOSSSHIELDSLEVEL1,
            "requires_power": True,
        },
        UpgradeId.PROTOSSSHIELDSLEVEL2: {
            "ability": AbilityId.FORGERESEARCH_PROTOSSSHIELDSLEVEL2,
            "required_building": UnitTypeId.TWILIGHTCOUNCIL,
            "required_upgrade": UpgradeId.PROTOSSSHIELDSLEVEL1,
            "requires_power": True,
        },
        UpgradeId.PROTOSSSHIELDSLEVEL3: {
            "ability": AbilityId.FORGERESEARCH_PROTOSSSHIELDSLEVEL3,
            "required_building": UnitTypeId.TWILIGHTCOUNCIL,
            "required_upgrade": UpgradeId.PROTOSSSHIELDSLEVEL2,
            "requires_power": True,
        },
    },
    UnitTypeId.FUSIONCORE: {
        UpgradeId.BATTLECRUISERENABLESPECIALIZATIONS: {
            "ability": AbilityId.FUSIONCORERESEARCH_RESEARCHBATTLECRUISERSPECIALIZATIONS
        },
        UpgradeId.LIBERATORAGRANGEUPGRADE: {"ability": AbilityId.FUSIONCORERESEARCH_RESEARCHBALLISTICRANGE},
        UpgradeId.MEDIVACINCREASESPEEDBOOST: {"ability": AbilityId.FUSIONCORERESEARCH_RESEARCHRAPIDREIGNITIONSYSTEM},
    },
    UnitTypeId.GHOSTACADEMY: {
        UpgradeId.ENHANCEDSHOCKWAVES: {"ability": AbilityId.GHOSTACADEMYRESEARCH_RESEARCHENHANCEDSHOCKWAVES},
        UpgradeId.PERSONALCLOAKING: {"ability": AbilityId.GHOSTACADEMYRESEARCH_RESEARCHPERSONALCLOAKING},
    },
    UnitTypeId.GREATERSPIRE: {
        UpgradeId.ZERGFLYERARMORSLEVEL1: {"ability": AbilityId.SPIRERESEARCH_ZERGFLYERARMOR1},
        UpgradeId.ZERGFLYERARMORSLEVEL2: {
            "ability": AbilityId.SPIRERESEARCH_ZERGFLYERARMOR2,
            "required_building": UnitTypeId.LAIR,
            "required_upgrade": UpgradeId.ZERGFLYERARMORSLEVEL1,
        },
        UpgradeId.ZERGFLYERARMORSLEVEL3: {
            "ability": AbilityId.SPIRERESEARCH_ZERGFLYERARMOR3,
            "required_building": UnitTypeId.HIVE,
            "required_upgrade": UpgradeId.ZERGFLYERARMORSLEVEL2,
        },
        UpgradeId.ZERGFLYERWEAPONSLEVEL1: {"ability": AbilityId.SPIRERESEARCH_ZERGFLYERATTACK1},
        UpgradeId.ZERGFLYERWEAPONSLEVEL2: {
            "ability": AbilityId.SPIRERESEARCH_ZERGFLYERATTACK2,
            "required_building": UnitTypeId.LAIR,
            "required_upgrade": UpgradeId.ZERGFLYERWEAPONSLEVEL1,
        },
        UpgradeId.ZERGFLYERWEAPONSLEVEL3: {
            "ability": AbilityId.SPIRERESEARCH_ZERGFLYERATTACK3,
            "required_building": UnitTypeId.HIVE,
            "required_upgrade": UpgradeId.ZERGFLYERWEAPONSLEVEL2,
        },
    },
    UnitTypeId.HATCHERY: {
        UpgradeId.BURROW: {"ability": AbilityId.LAIRRESEARCH_RESEARCHBURROW},
        UpgradeId.OVERLORDSPEED: {"ability": AbilityId.LAIRRESEARCH_OVERLORDSPEED},
    },
    UnitTypeId.HIVE: {
        UpgradeId.BURROW: {"ability": AbilityId.LAIRRESEARCH_RESEARCHBURROW},
        UpgradeId.OVERLORDSPEED: {"ability": AbilityId.LAIRRESEARCH_OVERLORDSPEED},
    },
    UnitTypeId.HYDRALISKDEN: {
        UpgradeId.EVOLVEGROOVEDSPINES: {"ability": AbilityId.HYDRALISKDENRESEARCH_EVOLVEGROOVEDSPINES},
        UpgradeId.EVOLVEMUSCULARAUGMENTS: {"ability": AbilityId.HYDRALISKDENRESEARCH_EVOLVEMUSCULARAUGMENTS},
    },
    UnitTypeId.INFESTATIONPIT: {
        UpgradeId.INFESTORENERGYUPGRADE: {"ability": AbilityId.INFESTATIONPITRESEARCH_EVOLVEINFESTORENERGYUPGRADE},
        UpgradeId.MICROBIALSHROUD: {"ability": AbilityId.INFESTATIONPITRESEARCH_EVOLVEAMORPHOUSARMORCLOUD},
        UpgradeId.NEURALPARASITE: {"ability": AbilityId.INFESTATIONPITRESEARCH_RESEARCHNEURALPARASITE},
    },
    UnitTypeId.LAIR: {
        UpgradeId.BURROW: {"ability": AbilityId.LAIRRESEARCH_RESEARCHBURROW},
        UpgradeId.OVERLORDSPEED: {"ability": AbilityId.LAIRRESEARCH_OVERLORDSPEED},
    },
    UnitTypeId.LURKERDENMP: {
        UpgradeId.DIGGINGCLAWS: {
            "ability": AbilityId.LURKERDENRESEARCH_EVOLVEDIGGINGCLAWS,
            "required_building": UnitTypeId.HIVE,
        },
        UpgradeId.LURKERRANGE: {
            "ability": AbilityId.LURKERDENRESEARCH_RESEARCHLURKERRANGE,
            "required_building": UnitTypeId.HIVE,
        },
    },
    UnitTypeId.ROACHWARREN: {
        UpgradeId.GLIALRECONSTITUTION: {
            "ability": AbilityId.ROACHWARRENRESEARCH_EVOLVEGLIALREGENERATION,
            "required_building": UnitTypeId.LAIR,
        },
        UpgradeId.TUNNELINGCLAWS: {
            "ability": AbilityId.ROACHWARRENRESEARCH_EVOLVETUNNELINGCLAWS,
            "required_building": UnitTypeId.LAIR,
        },
    },
    UnitTypeId.ROBOTICSBAY: {
        UpgradeId.EXTENDEDTHERMALLANCE: {
            "ability": AbilityId.ROBOTICSBAYRESEARCH_RESEARCHEXTENDEDTHERMALLANCE,
            "requires_power": True,
        },
        UpgradeId.GRAVITICDRIVE: {
            "ability": AbilityId.ROBOTICSBAYRESEARCH_RESEARCHGRAVITICDRIVE,
            "requires_power": True,
        },
        UpgradeId.OBSERVERGRAVITICBOOSTER: {
            "ability": AbilityId.ROBOTICSBAYRESEARCH_RESEARCHGRAVITICBOOSTER,
            "requires_power": True,
        },
    },
    UnitTypeId.SPAWNINGPOOL: {
        UpgradeId.ZERGLINGATTACKSPEED: {
            "ability": AbilityId.SPAWNINGPOOLRESEARCH_ZERGLINGATTACKSPEED,
            "required_building": UnitTypeId.HIVE,
        },
        UpgradeId.ZERGLINGMOVEMENTSPEED: {"ability": AbilityId.SPAWNINGPOOLRESEARCH_ZERGLINGMOVEMENTSPEED},
    },
    UnitTypeId.SPIRE: {
        UpgradeId.ZERGFLYERARMORSLEVEL1: {"ability": AbilityId.SPIRERESEARCH_ZERGFLYERARMOR1},
        UpgradeId.ZERGFLYERARMORSLEVEL2: {
            "ability": AbilityId.SPIRERESEARCH_ZERGFLYERARMOR2,
            "required_building": UnitTypeId.LAIR,
            "required_upgrade": UpgradeId.ZERGFLYERARMORSLEVEL1,
        },
        UpgradeId.ZERGFLYERARMORSLEVEL3: {
            "ability": AbilityId.SPIRERESEARCH_ZERGFLYERARMOR3,
            "required_building": UnitTypeId.HIVE,
            "required_upgrade": UpgradeId.ZERGFLYERARMORSLEVEL2,
        },
        UpgradeId.ZERGFLYERWEAPONSLEVEL1: {"ability": AbilityId.SPIRERESEARCH_ZERGFLYERATTACK1},
        UpgradeId.ZERGFLYERWEAPONSLEVEL2: {
            "ability": AbilityId.SPIRERESEARCH_ZERGFLYERATTACK2,
            "required_building": UnitTypeId.LAIR,
            "required_upgrade": UpgradeId.ZERGFLYERWEAPONSLEVEL1,
        },
        UpgradeId.ZERGFLYERWEAPONSLEVEL3: {
            "ability": AbilityId.SPIRERESEARCH_ZERGFLYERATTACK3,
            "required_building": UnitTypeId.HIVE,
            "required_upgrade": UpgradeId.ZERGFLYERWEAPONSLEVEL2,
        },
    },
    UnitTypeId.STARPORTTECHLAB: {
        UpgradeId.BANSHEECLOAK: {"ability": AbilityId.STARPORTTECHLABRESEARCH_RESEARCHBANSHEECLOAK},
        UpgradeId.BANSHEESPEED: {"ability": AbilityId.STARPORTTECHLABRESEARCH_BANSHEESPEED},
        UpgradeId.RAVENCORVIDREACTOR: {"ability": AbilityId.STARPORTTECHLABRESEARCH_RESEARCHRAVENENERGYUPGRADE},
    },
    UnitTypeId.TEMPLARARCHIVE: {
        UpgradeId.PSISTORMTECH: {"ability": AbilityId.TEMPLARARCHIVESRESEARCH_RESEARCHPSISTORM, "requires_power": True}
    },
    UnitTypeId.TWILIGHTCOUNCIL: {
        UpgradeId.ADEPTPIERCINGATTACK: {
            "ability": AbilityId.TWILIGHTCOUNCILRESEARCH_ADEPTRESEARCHPIERCINGUPGRADE,
            "requires_power": True,
        },
        UpgradeId.BLINKTECH: {
            "ability": AbilityId.TWILIGHTCOUNCILRESEARCH_RESEARCHSTALKERTELEPORT,
            "requires_power": True,
        },
        UpgradeId.CHARGE: {"ability": AbilityId.TWILIGHTCOUNCILRESEARCH_RESEARCHCHARGE, "requires_power": True},
    },
    UnitTypeId.ULTRALISKCAVERN: {
        UpgradeId.ANABOLICSYNTHESIS: {"ability": AbilityId.ULTRALISKCAVERNRESEARCH_EVOLVEANABOLICSYNTHESIS2},
        UpgradeId.CHITINOUSPLATING: {"ability": AbilityId.ULTRALISKCAVERNRESEARCH_EVOLVECHITINOUSPLATING},
    },
}
